// console.log(Math.floor(4.1))
// console.log(Math.floor(4.56766744565659))
// console.log(Math.floor(4.9))
// console.log(Math.round(5.9))
// console.log(Math.round(5.5))
// console.log(Math.round(5.2))
// console.log(Math.ceil(6.9))
// console.log(Math.ceil(6.5))
// console.log(Math.ceil(6.2))
// console.log(Math.random())
// console.log(Math.max(20,43,54))
// console.log(Math.min(20,43,54))
const arr = [10,20,40]
console.log(Math.max(...arr))
console.log(Math.sqrt(100))
const tools = ["py", "se", "cy", "ts"]
const randomData = Math.floor(Math.random() *1000)
console.log(`userName-${randomData}`)
console.log(arr.length)
console.log(Math.random() * arr.length)
const randomIndex = Math.floor(Math.random() * arr.length)
console.log(tools[randomIndex])
